
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - npm install

  pre_build:
    commands:
      - npm run test

  build:
    commands:
      - npm run build
      - cdk synth

  post_build:
    commands:
      - cdk destroy --force --all --context stack=A --require-approval never
      # - cdk deploy --context stack=A --require-approval never

artifacts:
  files:
    - cdk.out/**/*
    - package.json
    - package-lock.json
    - README.md
  discard-paths: yes